<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="4" passed="0">
  <reporter-output>
    <line>
      <![CDATA[About to begin executing Suite Suite]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test Test]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : SampleCase1.SampleCase]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : SampleCase1.SampleCase]]>
    </line>
    <line>
      <![CDATA[Test Method resides in tests.SampleCase1]]>
    </line>
    <line>
      <![CDATA[Test Status: Skipped]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : SampleCase1.SampleCase]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : SampleCase1.SampleCase]]>
    </line>
    <line>
      <![CDATA[Test Method resides in tests.SampleCase1]]>
    </line>
    <line>
      <![CDATA[Test Status: Skipped]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : SampleCase1.SampleCase]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : SampleCase1.SampleCase]]>
    </line>
    <line>
      <![CDATA[Test Method resides in tests.SampleCase1]]>
    </line>
    <line>
      <![CDATA[Test Status: Skipped]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : SampleCase1.SampleCase]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : SampleCase1.SampleCase]]>
    </line>
    <line>
      <![CDATA[Test Method resides in tests.SampleCase1]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="8031" started-at="2017-10-26T18:50:28Z" finished-at="2017-10-26T18:50:36Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="8031" started-at="2017-10-26T18:50:28Z" finished-at="2017-10-26T18:50:36Z">
      <class name="tests.SampleCase1">
        <test-method status="SKIP" signature="SampleCase()[pri:0, instance:tests.SampleCase1@523884b2]" name="SampleCase" duration-ms="2511" started-at="2017-10-26T14:50:28Z" finished-at="2017-10-26T14:50:31Z">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Test Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Test Failed
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at tests.SampleCase1.SampleCase(SampleCase1.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : SampleCase1.SampleCase]]>
            </line>
            <line>
              <![CDATA[Test Method resides in tests.SampleCase1]]>
            </line>
            <line>
              <![CDATA[Test Status: Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- SampleCase -->
        <test-method status="SKIP" signature="SampleCase()[pri:0, instance:tests.SampleCase1@523884b2]" name="SampleCase" duration-ms="1919" started-at="2017-10-26T14:50:31Z" finished-at="2017-10-26T14:50:33Z">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Test Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Test Failed
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at tests.SampleCase1.SampleCase(SampleCase1.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:963)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : SampleCase1.SampleCase]]>
            </line>
            <line>
              <![CDATA[Test Method resides in tests.SampleCase1]]>
            </line>
            <line>
              <![CDATA[Test Status: Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- SampleCase -->
        <test-method status="SKIP" signature="SampleCase()[pri:0, instance:tests.SampleCase1@523884b2]" name="SampleCase" duration-ms="1734" started-at="2017-10-26T14:50:33Z" finished-at="2017-10-26T14:50:35Z">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Test Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Test Failed
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at tests.SampleCase1.SampleCase(SampleCase1.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:963)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : SampleCase1.SampleCase]]>
            </line>
            <line>
              <![CDATA[Test Method resides in tests.SampleCase1]]>
            </line>
            <line>
              <![CDATA[Test Status: Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- SampleCase -->
        <test-method status="FAIL" signature="SampleCase()[pri:0, instance:tests.SampleCase1@523884b2]" name="SampleCase" duration-ms="1839" started-at="2017-10-26T14:50:35Z" finished-at="2017-10-26T14:50:36Z">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Test Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Test Failed
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at tests.SampleCase1.SampleCase(SampleCase1.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:963)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : SampleCase1.SampleCase]]>
            </line>
            <line>
              <![CDATA[Test Method resides in tests.SampleCase1]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- SampleCase -->
      </class> <!-- tests.SampleCase1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
